" .vimrc
" Maintained by: Ankit Goyal
" me@goyalankit.com
" http://goyalankit.com

" ----------------------------------------------------------------------------
" Vundle Config File.
" ----------------------------------------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
Bundle 'tacahiroy/ctrlp-funky'
Bundle 'scrooloose/nerdcommenter'
Bundle 'tpope/vim-surround'

" ack plugin
Bundle 'mileszs/ack.vim'

" Rails plugins thanks to Tim Pope & others
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-bundler'

" code completion
Bundle 'Raimondi/delimitMate'
Bundle 'tomtom/tcomment_vim'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"
Bundle "ervandew/supertab"

" vim ruby specific stuff
Bundle 'vim-ruby/vim-ruby'

" Optional:
Bundle "honza/vim-snippets"
Bundle "pangloss/vim-javascript"

Bundle "flazz/vim-colorschemes"
Bundle "vim-scripts/Align"

" Better buffers
Bundle 'jlanzarotta/bufexplorer'
Bundle "mattn/emmet-vim"

" Vim Advance
Bundle 'terryma/vim-multiple-cursors'
Bundle 'kchmck/vim-coffee-script'

" highlight whitespace
Bundle 'ntpeters/vim-better-whitespace'

" cpp
Plugin 'octol/vim-cpp-enhanced-highlight'

" Markdown related plugins
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" ruby inline execution
Bundle 't9md/vim-ruby-xmpfilter'

" airline plugin
Plugin 'bling/vim-airline'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on

" ---------------------------------------------------------------
" END of vundle plugin
" ---------------------------------------------------------------

" vim colorscheme
colorscheme vividchalk

syntax on
syntax enable
set nobackup
set nowritebackup
set noswapfile

" NERDTree settings
map <Leader>n :NERDTreeToggle<CR>
let g:NERDTreeWinPos = "right"
colorscheme vividchalk


"let NERDTreeDirArrows=0
"nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>gb :Gblame<cr>
let g:gitgutter_sign_column_always = 1

" Theme
"set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
"set nu
"set relativenumber
set background=dark
set guifont=Monaco:h13

" Funky ctrlp addon settings
let g:ctrlp_extensions = ['funky']
nnoremap <Leader>m :CtrlPFunky<Cr>
"nnoremap <C-b> :ctrlPBuffer<Cr>
nnoremap <Leader>M :execute 'CtrlPFunky ' . expand('<cword>')<Cr>
let g:ctrlp_funky_syntax_highlight = 1

" Remove sidebars
set guioptions-=T "remove toolbar
set guioptions-=r "remove right-hand scroll bar
set go-=L "remove right-hand scroll bar
set go-=M "remove right-hand scroll bar

" word wraps
set linebreak
set wrap

" Soft Tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Rails
let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_rails = 1

" DON'T USE arrow keys.
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" map tab navigation
for i in range(1,9)
  map <D-[eval(i)]> [eval(i)]gt
endfor
map <D-0> :tablast<Cr>

nnoremap ; :

" map explorer
nnoremap <C-e> :Exp<Cr>

let g:vim_markdown_folding_disabled=1
let g:cpp_class_scope_highlight = 1
let g:cpp_experimental_template_highlight = 1

" restore last editted position
source $VIMRUNTIME/vimrc_example.vim
set backupdir=~/tmp
set noundofile


autocmd FileType ruby nmap <buffer> <D-i> <Plug>(xmpfilter-mark)
autocmd FileType ruby xmap <buffer> <D-i> <Plug>(xmpfilter-mark)
autocmd FileType ruby imap <buffer> <D-i> <Plug>(xmpfilter-mark)

autocmd FileType ruby nmap <buffer> <D-r> <Plug>(xmpfilter-run)
autocmd FileType ruby xmap <buffer> <D-r> <Plug>(xmpfilter-run)
autocmd FileType ruby imap <buffer> <D-r> <Plug>(xmpfilter-run)

" start airline for single tab
set laststatus=2
